// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtLEvea_lCOTuj1E9nzftucpQd0JcOPFc',
    appId: '1:82560807642:web:d09dcabf6482b19f9c2be3',
    messagingSenderId: '82560807642',
    projectId: 'onequiz-bd727',
    authDomain: 'onequiz-bd727.firebaseapp.com',
    storageBucket: 'onequiz-bd727.appspot.com',
    measurementId: 'G-7JK29PN0N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj2uzT9dKh4iLUb5I0UZ7sbrxcsyN8wxc',
    appId: '1:82560807642:android:9d9e15a29da1b1ea9c2be3',
    messagingSenderId: '82560807642',
    projectId: 'onequiz-bd727',
    storageBucket: 'onequiz-bd727.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_wBPQOQr6uj6ytawMQ4Z3SZXJjKy4Xu4',
    appId: '1:82560807642:ios:16dc2cc0c6c7c9779c2be3',
    messagingSenderId: '82560807642',
    projectId: 'onequiz-bd727',
    storageBucket: 'onequiz-bd727.appspot.com',
    iosClientId: '82560807642-44jeh028l92gou4dsoae78031108o3r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.onequizadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_wBPQOQr6uj6ytawMQ4Z3SZXJjKy4Xu4',
    appId: '1:82560807642:ios:16dc2cc0c6c7c9779c2be3',
    messagingSenderId: '82560807642',
    projectId: 'onequiz-bd727',
    storageBucket: 'onequiz-bd727.appspot.com',
    iosClientId: '82560807642-44jeh028l92gou4dsoae78031108o3r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.onequizadmin',
  );
}
